security:
  oauth2:
    authorization:
      check-token-access: permitAll()
      
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_server
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  data:
    jpa: 
      repositories:
        enabled: true
  jpa: 
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: validate 
    show-sql: true
    properties:
      hibernate: 
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext    
server:
  port: 9999
  context-path: /uaa
logging:
  level:
    org.springframework.security: DEBUG